language: node_js
node_js: node
script: npm run predeploy
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: u6gMdxFO+KrUWlcihmJH6OVoAl6f2pLPgx+4NNr6sJxL4f8KYqvZEaCj0RvkjCQASzHU8juLpz1Y31fagraxEiC5qiyXffiEKi0LaSK6/bsK+ZscK1+apwvf4rdhfIswOeodBXl3gNwdz6GQPsvclkA/U89J2Yfd+YR3t5lo0b4ZW0J6xFq4oCqs72om6wALKfGRG+7c1Hz6KVOVmVshpYFt0/kW3pD7BOqYRHgiK+mSna0uuFmLfOJgcb/LdKTS06yg+Yc5XmtJW4+oByxvfSTLMmPorkgegZNtvWFRBktA3uPO360ZCgGyAI8Rf5ZWqq7VDYL1OowYn+NBi10JF0huRFbCPzM5i8sc8yn6un4JGFzeeyKwYyx3aQWCHdDOwq6NUqYEDX3cmmDZWAr+tQqRfizsuPjCkbLHm7JKxWEJWTFshwv/fWhUHTlESM6SvIAlfh7AcU/ZtGxwegDPAxycijlhntcxKGrIeB422U8/MuNAK0L1BxcqpGkKcCbU0uJVZ81higqV6x/rYiSxpGcIdVNXlevSKGgSrw3lfVVLMZw1AWpLGyq5FlOQ9VVFn79OkP+WkUPNRkAq60Qk+JSBr4LmPS6GdMFQxI8T6haHUq1MVNjMfw5G2GWj9rTyjE8Z9JNgFNXhBqxtz+X7w5yVHvkFCHMGw6X6XUMnorA=
